[project]
name = "agentic-rag-with-langgraph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "langchain>=1.0",
    "langchain-chroma>=1.0",
    "langchain-openai>=1.0",
    "langchain-tavily>=0.2",
    "langgraph>=1.0",
    "nest-asyncio>=1.6.0",
    "pandas>=2.3.1",
    "pydantic>=2.11.7",
    "pyppeteer>=2.0.0",
    "python-dotenv>=1.1.1",
    "tqdm>=4.67.1",
]
